# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e779e5ae2b89c7681d529599e649ee9adad15912dcf76993ed9f27d29bbaeffb53ae8459c5f5be682958a9d95f4b7e03e12a9b7a717927770afd562d4c76ceac

test:
  secret_key_base: 9d491d62d799b6180fa74112a1a46edbb26cb5189c4f24018359241cc07674f530e05409bb5dba6926fc2f09ac8abff924866a57abf2d0504acb3cd6ff619f38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
